[workspace]
members = [
  "packages/api",
  "packages/desktop",
  "packages/mobile",
  "packages/ui",
  "packages/web",
]
resolver = "3"

[workspace.dependencies]
chrono = { features = ["serde"], version = "0.4" }
dioxus = { version = "0.7.1" }
gloo-timers = { features = ["futures"], version = "0.4" }
maximal-lottery = "0.1.1"
nanoid = "0.5"
num-rational = "0.4"
num-traits = "0.2"
nutype = { features = ["serde"], version = "0.7" }
opentelemetry = { features = ["trace"], version = "0.32" }
opentelemetry-otlp = { features = ["grpc-tonic", "trace"], version = "0.32" }
opentelemetry_sdk = { features = ["rt-tokio", "trace"], version = "0.32" }
serde = { features = ["derive"], version = "1" }
sqlx = { default-features = false, features = [
  "chrono",
  "macros",
  "migrate",
  "postgres",
  "runtime-tokio",
], version = "0.8" }
tokio = { version = "1" }
tracing = "0.1"
tracing-opentelemetry = "0.33"
tracing-subscriber = { features = [
  "env-filter",
  "fmt",
  "registry",
], version = "0.3" }
wasm-bindgen = "0.2.126"

# workspace
api = { path = "packages/api" }
ui = { path = "packages/ui" }
