[workspace]
members = [
  "packages/api",
  "packages/web",
]
resolver = "3"

[workspace.package]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
base64 = "0.23.0"
chrono = { features = ["serde"], version = "0.4" }
dioxus = { version = "0.7.1" }
gloo-timers = { features = ["futures"], version = "0.4" }
http = "1.4.2"
maximal-lottery = "0.1.1"
nanoid = "0.5"
num-rational = "0.4"
num-traits = "0.2"
nutype = { features = ["serde"], version = "0.7" }
opentelemetry = { features = ["trace"], version = "0.32" }
opentelemetry-otlp = { default-features = false, features = [
  "http-proto",
  "reqwest-blocking-client",
  "reqwest-rustls",
  "trace",
], version = "0.32" }
opentelemetry_sdk = { features = ["rt-tokio", "trace"], version = "0.32" }
serde = { features = ["derive"], version = "1" }
sqlx = { default-features = false, features = [
  "chrono",
  "macros",
  "migrate",
  "postgres",
  "runtime-tokio",
  "tls-rustls-ring-webpki",
], version = "0.8" }
subtle = "2.6.1"
tokio = { version = "1" }
tower-http = { features = ["auth", "trace"], version = "0.7.0" }
tracing = "0.1"
tracing-opentelemetry = "0.33"
tracing-subscriber = { features = [
  "env-filter",
  "fmt",
  "registry",
], version = "0.3" }
wasm-bindgen = "0.2.126"
web-sys = { features = ["Document", "Element", "Window"], version = "0.3" }

# workspace
api = { path = "packages/api" }
