volumes:
  caddy_data:

services:
  caddy:
    image: caddy:2
    depends_on:
      - app
    environment:
      CADDY_EMAIL: ${CADDY_EMAIL:?required}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?required}
      DOMAIN: ${DOMAIN:?required}
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data

  app:
    environment:
      DATABASE_URL: ${DATABASE_URL:?required}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:?required}
    image: ghcr.io/${GITHUB_REPOSITORY:?required}:${IMAGE_TAG:-latest}
    restart: unless-stopped
