version: "1"
name: dioxus-maximal-lottery

projects:
  - name: dioxus-maximal-lottery
    environments:
      - name: prd
        services:
          - type: web
            name: maximal-lottery-prd
            runtime: image
            plan: free
            image:
              url: ghcr.io/buffbirb/maximal-lottery-web:prd
              creds:
                fromRegistryCreds:
                  name: "dioxus-maximal-lottery Render GHCR Deploy"
            envVars:
              - key: DATABASE_URL
                sync: false
              - key: IP
                value: 0.0.0.0
              - key: OTEL_EXPORTER_OTLP_ENDPOINT
                sync: false
