CREATE TABLE polls (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    share_id VARCHAR(21) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    deadline TIMESTAMPTZ,
    hide_results BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE options (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
    idx INTEGER NOT NULL,
    label VARCHAR(200) NOT NULL,
    UNIQUE (poll_id, idx)
);

CREATE TABLE votes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE vote_rankings (
    vote_id BIGINT NOT NULL REFERENCES votes(id) ON DELETE CASCADE,
    option_id BIGINT NOT NULL REFERENCES options(id) ON DELETE CASCADE,
    tier INTEGER NOT NULL,
    PRIMARY KEY (vote_id, option_id)
);
