name: Deploy Render

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string

permissions: {}

jobs:
  deploy:
    name: Deploy Render ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      contents: read

    steps:
      - name: Deploy Render
        env:
          IMAGE_TAG: ${{ inputs.image-tag }}
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
          REPOSITORY: ${{ github.repository }}
        run: |
          img_url="ghcr.io/${REPOSITORY,,}:${IMAGE_TAG}"
          encoded_img_url=$(jq -nr --arg v "${img_url}" '$v|@uri')
          curl -fsSL -X POST "${RENDER_DEPLOY_HOOK}?imgURL=${encoded_img_url}"
